version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

workflows:
  build:
    jobs: 
      - build: 
        context:
          - docker-context
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
        auth:
          username: lawrencewhalen
          password: MY_DOCKER_VAR
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
